const LOCATION_TTL_SECONDS = Number(
  process.env.LOCATION_TTL_SECONDS || 180
);
const ONLINE_TTL_SECONDS = Number(
  process.env.ONLINE_TTL_SECONDS || 300
);
const MAX_LOCATION_RATE_PER_SEC = Number(
  process.env.MAX_LOCATION_RATE_PER_SEC || 1
);
const DEFAULT_SEARCH_RADIUS_METERS = Number(
  process.env.DEFAULT_SEARCH_RADIUS_METERS || 3000
);
const AVAILABLE_LIMIT_DEFAULT = Number(
  process.env.AVAILABLE_LIMIT_DEFAULT || 20
);
const FORCE_OFFLINE_WHEN_BUSY =
  String(process.env.FORCE_OFFLINE_WHEN_BUSY || "false") ===
  "true";

module.exports = {
  LOCATION_TTL_SECONDS,
  ONLINE_TTL_SECONDS,
  MAX_LOCATION_RATE_PER_SEC,
  DEFAULT_SEARCH_RADIUS_METERS,
  AVAILABLE_LIMIT_DEFAULT,
  FORCE_OFFLINE_WHEN_BUSY
};
