services:
  kafka-1:
    image: confluentinc/cp-kafka:7.6.1
    profiles: ["kafka-prodlike"]
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-1:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_INTERNAL_TOPIC_RF:-3}
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: ${KAFKA_INTERNAL_TOPIC_MIN_ISR:-2}
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${KAFKA_INTERNAL_TOPIC_RF:-3}
      KAFKA_DEFAULT_REPLICATION_FACTOR: ${KAFKA_TOPIC_RF:-3}
      KAFKA_MIN_INSYNC_REPLICAS: ${KAFKA_TOPIC_MIN_ISR:-2}
      KAFKA_NUM_PARTITIONS: ${KAFKA_TOPIC_DEFAULT_PARTITIONS:-12}
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    networks:
      - backend

  kafka-2:
    image: confluentinc/cp-kafka:7.6.1
    profiles: ["kafka-prodlike"]
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 102
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-2:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_INTERNAL_TOPIC_RF:-3}
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: ${KAFKA_INTERNAL_TOPIC_MIN_ISR:-2}
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${KAFKA_INTERNAL_TOPIC_RF:-3}
      KAFKA_DEFAULT_REPLICATION_FACTOR: ${KAFKA_TOPIC_RF:-3}
      KAFKA_MIN_INSYNC_REPLICAS: ${KAFKA_TOPIC_MIN_ISR:-2}
      KAFKA_NUM_PARTITIONS: ${KAFKA_TOPIC_DEFAULT_PARTITIONS:-12}
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    networks:
      - backend

  kafka-3:
    image: confluentinc/cp-kafka:7.6.1
    profiles: ["kafka-prodlike"]
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 103
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-3:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: ${KAFKA_INTERNAL_TOPIC_RF:-3}
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: ${KAFKA_INTERNAL_TOPIC_MIN_ISR:-2}
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${KAFKA_INTERNAL_TOPIC_RF:-3}
      KAFKA_DEFAULT_REPLICATION_FACTOR: ${KAFKA_TOPIC_RF:-3}
      KAFKA_MIN_INSYNC_REPLICAS: ${KAFKA_TOPIC_MIN_ISR:-2}
      KAFKA_NUM_PARTITIONS: ${KAFKA_TOPIC_DEFAULT_PARTITIONS:-12}
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    networks:
      - backend
