export enum RideState {
  CREATED = 'CREATED',
  SEARCHING_DRIVER = 'SEARCHING_DRIVER',
  DRIVER_ASSIGNED = 'DRIVER_ASSIGNED',
  DRIVER_ARRIVING = 'DRIVER_ARRIVING',
  DRIVER_AT_PICKUP = 'DRIVER_AT_PICKUP',
  TRIP_STARTED = 'TRIP_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  ARRIVING_DESTINATION = 'ARRIVING_DESTINATION',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}

export enum PaymentState {
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  TIMEOUT = 'TIMEOUT',
  RETRYING = 'RETRYING',
  REFUNDED = 'REFUNDED',
  UNPAID = 'UNPAID'
}
