/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/payments': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List payments */
    get: {
      parameters: {
        query?: {
          limit?: number;
          cursor?: string;
          sort?: 'createdAt' | '-createdAt';
          status?: string;
          rideId?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Payment list */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PaymentListResponse'];
          };
        };
        /** @description Invalid query */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    /** Create payment */
    post: {
      parameters: {
        query?: never;
        header: {
          'Idempotency-Key': components['parameters']['IdempotencyKey'];
        };
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['PaymentCreateRequest'];
        };
      };
      responses: {
        /** @description Payment created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PaymentResponse'];
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Idempotency conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/payments/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get payment by id */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: components['parameters']['PaymentId'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Payment */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PaymentResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update payment status */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: components['parameters']['PaymentId'];
        };
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['PaymentStatusUpdate'];
        };
      };
      responses: {
        /** @description Payment */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['PaymentResponse'];
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Invalid status transition */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    trace?: never;
  };
  '/v1/payments/{id}/vietqr-codes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get VietQR data for a payment */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: components['parameters']['PaymentId'];
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description VietQR data */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['VietQrResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description VietQR not available */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Payment: {
      id: string;
      rideId: string;
      userId?: string;
      amount: string;
      currency: string;
      method?: string;
      status: string;
      /** Format: date-time */
      statusUpdatedAt: string;
      failureReason?: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      vietqr?: components['schemas']['VietQrData'];
    };
    VietQrData: {
      payload?: string;
      qrUrl?: string;
      reference?: string;
      /** Format: date-time */
      expiresAt?: string;
    };
    PaymentCreateRequest: {
      rideId: string;
      amount: string | number;
      currency: string;
      method?: string;
      userId?: string;
      note?: string;
    };
    PaymentStatusUpdate: {
      status: string;
      failureReason?: string;
    };
    PaymentResponse: {
      data?: components['schemas']['Payment'];
    };
    PaymentListResponse: {
      data?: components['schemas']['Payment'][];
      nextCursor?: string;
    };
    VietQrResponse: {
      data?: {
        paymentId?: string;
        rideId?: string;
        amount?: string;
        currency?: string;
        vietqr?: components['schemas']['VietQrData'];
      };
    };
    ErrorResponse: {
      error?: {
        code?: string;
        message?: string;
        details?: string[];
      };
      traceId?: string;
    };
  };
  responses: never;
  parameters: {
    IdempotencyKey: string;
    PaymentId: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
