FROM node:20-alpine

WORKDIR /app

COPY apps/admin-dashboard/package*.json ./
RUN npm install

COPY apps/admin-dashboard ./

EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
