#!/usr/bin/env bash

# Shared metadata for test cases 1..100.
# Cases 1..10 are aligned to level1.docx (Context and Input columns).

get_case_context() {
  case "$1" in
    1) echo "Hệ thống hoạt động bình thường, chưa tồn tại user." ;;
    2) echo "User đã tồn tại trong hệ thống." ;;
    3) echo "User đã login, driver available." ;;
    4) echo "User đã có ít nhất 1 booking." ;;
    5) echo "Driver tồn tại trong hệ thống." ;;
    6) echo "Tạo booking thành công." ;;
    7) echo "AI ETA service hoạt động." ;;
    8) echo "Pricing service hoạt động." ;;
    9) echo "Booking đã được tạo." ;;
    10) echo "User đang login." ;;
    11) echo "User gửi request tạo booking nhưng thiếu field bắt buộc." ;;
    12) echo "Input sai kiểu dữ liệu (string thay vì float)." ;;
    13) echo "Không có driver online trong khu vực." ;;
    14) echo "User chọn phương thức thanh toán không tồn tại." ;;
    15) echo "Pickup = Drop." ;;
    16) echo "Không có nhu cầu (off-peak), demand_index = 0, supply_index = 1." ;;
    17) echo "Gọi Fraud detection thiếu dữ liệu." ;;
    18) echo "User dùng token hết hạn." ;;
    19) echo "User gửi request giống nhau 2 lần (same idempotency_key)." ;;
    20) echo "Client gửi request quá lớn." ;;
    21) echo "Booking Service gọi AI ETA service." ;;
    22) echo "Booking cần tính giá." ;;
    23) echo "AI Agent cần chọn driver." ;;
    24) echo "Booking hoàn chỉnh." ;;
    25) echo "Booking mới được tạo." ;;
    26) echo "Booking đã assign driver." ;;
    27) echo "Driver accept chuyến." ;;
    28) echo "AI Agent cần context." ;;
    29) echo "Request đi qua API Gateway." ;;
    30) echo "Pricing service chậm (simulate timeout)." ;;
    31) echo "Transaction tao booking thanh cong." ;;
    32) echo "Loi xay ra sau khi insert DB." ;;
    33) echo "Payment fail sau khi booking duoc tao." ;;
    34) echo "Client retry request trung lap." ;;
    35) echo "2 request booking chay cung luc." ;;
    36) echo "Distributed transaction (Booking -> Payment -> Notification)." ;;
    37) echo "Payment fail sau booking, can compensation." ;;
    38) echo "DB update + publish event (outbox pattern)." ;;
    39) echo "Network fail khi goi Payment service." ;;
    40) echo "Transaction phuc tap voi nhieu buoc DB operation." ;;
    41) echo "ETA model runs normally." ;;
    42) echo "Demand is high for surge scenario." ;;
    43) echo "Suspicious transaction should be flagged by fraud model." ;;
    44) echo "Recommendation should return top drivers." ;;
    45) echo "Forecast model receives historical data." ;;
    46) echo "Multiple model versions are available." ;;
    47) echo "Real-time AI service under many requests." ;;
    48) echo "Input distribution changes over time (drift)." ;;
    49) echo "Model crashes and system must fallback." ;;
    50) echo "Abnormal/outlier input provided." ;;
    51) echo "Many drivers are available; nearest should be selected." ;;
    52) echo "Drivers have different ratings." ;;
    53) echo "Agent must balance ETA vs price tradeoff." ;;
    54) echo "Flow needs both ETA and Pricing tools." ;;
    55) echo "Context is missing some driver data." ;;
    56) echo "ETA service/tool fails temporarily." ;;
    57) echo "Driver list contains offline driver." ;;
    58) echo "Agent decision must be logged with trace." ;;
    59) echo "Many requests are handled in parallel." ;;
    60) echo "AI model fails; rule-based fallback required." ;;
    61) echo "Many users create bookings at same time." ;;
    62) echo "ETA service is under high load." ;;
    63) echo "Pricing service receives traffic spike." ;;
    64) echo "Kafka receives very high event throughput." ;;
    65) echo "DB connection pool is stressed by concurrent access." ;;
    66) echo "Repeated requests should leverage cache." ;;
    67) echo "Gateway traffic exceeds configured threshold." ;;
    68) echo "Performance load test with p95 latency target." ;;
    69) echo "Peak-hour load ramps up gradually." ;;
    70) echo "Platform supports autoscaling (K8S/Swarm)." ;;
    71) echo "Driver service is down during booking flow." ;;
    72) echo "Pricing service times out during booking flow." ;;
    73) echo "Kafka broker is down during publish." ;;
    74) echo "Primary DB is down and failover/recovery is required." ;;
    75) echo "Repeated calls to failing dependency should trigger circuit breaker." ;;
    76) echo "Only part of the system fails." ;;
    77) echo "Temporary dependency error should use exponential backoff retry." ;;
    78) echo "Service mesh routing path has failure." ;;
    79) echo "Network partition between services." ;;
    80) echo "System is overloaded; graceful degradation required." ;;
    81) echo "API receives SQL injection attempt from user input." ;;
    82) echo "User submits script payload for XSS attempt." ;;
    83) echo "Attacker tampers JWT payload/claims." ;;
    84) echo "User without admin role tries admin API." ;;
    85) echo "Attacker sends abusive high-rate traffic." ;;
    86) echo "Replay old transaction request (idempotency attack)." ;;
    87) echo "Sensitive data stored in DB should be encrypted at rest." ;;
    88) echo "Service-to-service communication must enforce mTLS." ;;
    89) echo "RBAC enforcement for driver/user calling admin API." ;;
    90) echo "Sensitive data in logs/response must be masked." ;;
    91) echo "Request sent without token." ;;
    92) echo "Token payload/signature is tampered." ;;
    93) echo "Token is expired." ;;
    94) echo "Service A calls Service B without valid client cert." ;;
    95) echo "USER role tries to call admin endpoint." ;;
    96) echo "Driver tries to access another user's data." ;;
    97) echo "Client tries to bypass API gateway and call internal service directly." ;;
    98) echo "Client spams endpoint over rate limit threshold." ;;
    99) echo "Transport should enforce encrypted channel (HTTPS/mTLS)." ;;
    100) echo "Security audit logging for login and API action trace." ;;
    *) echo "" ;;
  esac
}

get_case_input() {
  case "$1" in
    1) echo '{"email":"user@test.com","password":"123456","name":"Test User"}' ;;
    2) echo '{"email":"user@test.com","password":"123456"}' ;;
    3) echo '{"pickup":{"lat":10.76,"lng":106.66},"drop":{"lat":10.77,"lng":106.70},"distance_km":5}' ;;
    4) echo 'GET /bookings?user_id=123' ;;
    5) echo '{"driver_id":"DRV001","status":"ONLINE"}' ;;
    6) echo '{"pickup":{"lat":10.76,"lng":106.66},"drop":{"lat":10.77,"lng":106.70},"distance_km":5}' ;;
    7) echo '{"distance_km":5,"traffic_level":0.5}' ;;
    8) echo '{"distance_km":5,"demand_index":1.0}' ;;
    9) echo '{"user_id":"USR123","message":"Your ride is confirmed"}' ;;
    10) echo 'Header: Authorization Bearer token' ;;
    11) echo '{"drop":{"lat":10.77,"lng":106.70}}' ;;
    12) echo '{"pickup":{"lat":"abc","lng":106.66},"drop":{"lat":10.77,"lng":106.70}}' ;;
    13) echo 'Booking hợp lệ' ;;
    14) echo '{"payment_method":"invalid_card"}' ;;
    15) echo '{"distance_km":0}' ;;
    16) echo '{"distance_km":5,"demand_index":0,"supply_index":1}' ;;
    17) echo '{"user_id":"USR123"}' ;;
    18) echo 'Header: Authorization Bearer expired_token' ;;
    19) echo 'Same booking payload + same idempotency_key sent twice' ;;
    20) echo 'JSON payload > 1MB' ;;
    21) echo '{"pickup":{"lat":10.76,"lng":106.66},"drop":{"lat":10.77,"lng":106.70}}' ;;
    22) echo '{"pickup":{"lat":10.76,"lng":106.66},"drop":{"lat":10.77,"lng":106.70}}' ;;
    23) echo 'danh sách driver từ service' ;;
    24) echo 'request booking + payment method' ;;
    25) echo 'Bước 1: User đặt xe; Bước 2: Booking Service tạo booking; Bước 3: Publish event lên Kafka; Bước 4: service khác nhận event' ;;
    26) echo 'driver_id' ;;
    27) echo '{"booking_id":"BK123","status":"ACCEPTED"}' ;;
    28) echo 'request từ AI Agent' ;;
    29) echo '/booking endpoint' ;;
    30) echo 'simulate timeout' ;;
    31) echo 'request /booking' ;;
    32) echo 'simulate loi sau buoc tao booking' ;;
    33) echo 'booking + payment' ;;
    34) echo 'cung Idempotency-Key' ;;
    35) echo '2 request booking song song' ;;
    36) echo 'full flow' ;;
    37) echo 'simulate failure' ;;
    38) echo 'create booking' ;;
    39) echo 'simulate timeout' ;;
    40) echo 'User dat xe -> tao booking -> tinh gia -> thanh toan -> assign driver' ;;
    41) echo 'distance=5km' ;;
    42) echo '{"demand_index":2}' ;;
    43) echo 'Suspicious transaction features for fraud score' ;;
    44) echo 'Input driver candidates for top-3 recommendation' ;;
    45) echo 'Historical data request for demand forecast' ;;
    46) echo 'Request including model version dimension' ;;
    47) echo 'Burst of AI inference requests' ;;
    48) echo 'New input distribution for drift check' ;;
    49) echo 'simulate_model_crash=true' ;;
    50) echo '{"distance_km":1000}' ;;
    51) echo 'D1:5km, D2:2km, D3:3km' ;;
    52) echo 'D1:distance=2km,rating=4.0; D2:distance=3km,rating=4.9' ;;
    53) echo 'A:ETA=5min,price=50k; B:ETA=8min,price=40k' ;;
    54) echo 'Flow requiring both ETA and Pricing tool calls' ;;
    55) echo 'Flow with missing driver context fields' ;;
    56) echo 'Flow with ETA service failure' ;;
    57) echo 'Driver list includes offline candidate' ;;
    58) echo 'Flow with x-trace-id for decision logging' ;;
    59) echo 'Parallel requests to agent endpoint' ;;
    60) echo 'Flow with model crash for rule fallback' ;;
    61) echo '1000 req/s to /booking' ;;
    62) echo '500 req/s to ETA service' ;;
    63) echo 'Spike load to Pricing API' ;;
    64) echo 'Thousands of ride_requested events/sec' ;;
    65) echo 'High concurrent DB access requests' ;;
    66) echo 'Repeated same-request pattern for cache hit-rate' ;;
    67) echo 'Traffic burst above gateway threshold' ;;
    68) echo 'Load test and measure p95 latency' ;;
    69) echo 'Gradual ramp-up peak-hour load' ;;
    70) echo 'Increase CPU/memory load to trigger scale-up' ;;
    71) echo 'User creates booking while Driver service is down' ;;
    72) echo 'Create booking while Pricing times out' ;;
    73) echo 'Publish ride_requested while Kafka is down' ;;
    74) echo 'DB query/booking while primary DB restart/failover' ;;
    75) echo 'Repeated calls to failing Pricing dependency' ;;
    76) echo 'Booking flow during partial outage' ;;
    77) echo 'Retry request after transient failure (1s->2s->4s)' ;;
    78) echo 'Request through mesh route with routing failure' ;;
    79) echo 'Simulated network split between services' ;;
    80) echo 'User booking request under overload/failure' ;;
    81) echo '{"email":"'\'' OR 1=1 --","password":"anything"}' ;;
    82) echo '<script>alert('\''hack'\'')</script>' ;;
    83) echo 'JWT payload tampered: sub->admin_001, role->ADMIN' ;;
    84) echo 'USER token calls admin API' ;;
    85) echo 'POST /booking spam >1000 requests/sec' ;;
    86) echo 'Replay same payment request payload' ;;
    87) echo 'Sensitive card_number data at rest' ;;
    88) echo 'Service request without valid mTLS certificate' ;;
    89) echo 'DRIVER role token calls admin API' ;;
    90) echo 'Payment response/logging path with sensitive fields' ;;
    91) echo 'GET /booking without Authorization header' ;;
    92) echo 'JWT with tampered signature/payload' ;;
    93) echo 'JWT with exp < current_time' ;;
    94) echo 'Service-to-service request without valid cert' ;;
    95) echo 'Token role=USER calls /admin/dashboard' ;;
    96) echo 'Driver calls /users/{user_id}' ;;
    97) echo 'Direct call to internal service bypassing gateway' ;;
    98) echo 'Client spam >100 requests/sec' ;;
    99) echo 'HTTP transport request without TLS' ;;
    100) echo 'Login + protected API call with traceable metadata' ;;
    *) echo "" ;;
  esac
}
